# @format

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://jonasgwt.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jonas Goh" # the name of your site, e.g. ACME Corp.
tagline: "Goh Wei Tai Jonas"
description: "Hello, I'm Goh Wei Tai Jonas, a Y2 NUS CS student. 
I am interested in software engineering and I'm excited about pursuing a career in that field. 
During my free time, I enjoy working on side projects and making use of the skills I learned to create an impact. 
I am excited about learning new skills and frameworks that can help me better myself and keep up with the progress of technology."
logo: /favicon.png
social:
  name: Jonas Goh
  links:
    - https://www.linkedin.com/in/jonasgwt/
    - https://github.com/jonasgwt
